/*
 * Lcd_cmd.h
 *
 *  Created on: ١٣‏/٠٩‏/٢٠٢٢
 *      Author: HP
 */

#ifndef HAL_LCD_LCD_CMD_H_
#define HAL_LCD_LCD_CMD_H_

#define LCD_CMD_DISPLAY_ON_CURSOR_BLINK		0X0E
#define LCD_CMD_DISPLAY_ON_CURSOR_BLINK2	0X0F
#define LCD_CMD_SHIF_CURSOR_POS_LEFT		0X10
#define LCD_CMD_SHIF_CURSOR_POS_RIGHT		0X14
#define LCD_CMD_SHIF_ENTIRE_DISPLAY_LEFT	0X18
#define LCD_CMD_SHIF_ENTIRE_DISPLAY_RIGHT	0X1C
#define LCD_CMD_CURSOR_BEGIN_1ST_LINE		0X80
#define LCD_CMD_CURSOR_BEGIN_2ND_LINE		0XC0
#define LCD_CMD_D4_TO_D7_4_BIT				0X28
#define LCD_CMD_D0_TO_D7_8_BIT				0X38
#define LCD_CMD_4_BIT_MODE					0X32
#define LCD_CMD_4_BIT_MODE2					0X33

#define LCD_CMD_CLEAR_DISPLAY			0X1
#define LCD_CMD_RETURN_HOME				0X2
#define LCD_CMD_SHIFT_CURSOR_LEFT		0X4
#define LCD_CMD_SHIFT_CURSOR_RIGHT		0X6
#define LCD_CMD_SHIFT_DISPLAY_RIGHT		0X5
#define LCD_CMD_SHIFT_DISPLAY_LEFT		0X7
#define LCD_CMD_DISPLAY_OFF_CURSOR_OFF	0X8
#define LCD_CMD_DISPLAY_OFF_CURSOR_ON	0XA
#define LCD_CMD_DISPLAY_ON_CURSOR_OFF	0XC








#endif /* HAL_LCD_LCD_CMD_H_ */
